// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://lodpbrcaxnktfbdbsfyz.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZHBicmNheG5rdGZiZGJzZnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjUzNzMsImV4cCI6MjA2MzQwMTM3M30._n8XW_NNSRNZ9NDoj7IWD8zGywG2UVpql85oKHW0Ta4';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'X-Client-Info': 'lovable-app/1.0.0',
    },
  },
});